org: rauhaanrizvi
app: gamereviews-serverless
service: gamereviews-serverless
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x

functions:
  api:
    handler: app.handler
    events:
      - httpApi: "*"
